### ISSUE TITLE
JSONObject["face_detection"] not found.

### ISSUE THREAD

**Issue by Creatifcookie** [shiffman/Rekognition-for-Processing#13]
I am getting the error when running the examples.

JSONObject["face_detection"] not found.

Using Processing 2.0, what can be the issue? Any ideas.

![screen shot 2015-04-08 at 11 56 58 pm](https://cloud.githubusercontent.com/assets/9595901/7060221/fc97c10e-de4a-11e4-9979-1be8d2161824.png)
![screen shot 2015-04-08 at 11 56 43 pm](https://cloud.githubusercontent.com/assets/9595901/7060222/fc97e774-de4a-11e4-9c18-2fe52af24baa.png)

**Comment by shiffman** [comment]
Did you register for an API key and include those keys in a `key.txt` file in the data folder?

**Comment by Creatifcookie** [comment]
OK. I rechecked it and I saved my txt file wrong! Needed to change the formatting to rich text. Thanks for making me think lol.
